name: stroke-predict-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - shap
  - xgboost
  - imbalanced-learn
  - joblib
